services:
  # Base de données MySQL
  - type: database
    name: library-db
    databaseName: library_db
    user: root
    plan: free # Vous pouvez changer pour un plan payant si besoin

  # Backend NestJS
  - type: web
    name: library-api
    env: docker
    dockerContext: .
    dockerFilePath: ./Dockerfile
    plan: starter
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 3000
      - key: DB_HOST
        fromDatabase:
          name: library-db
          property: host
      - key: DB_PORT
        value: 3306
      - key: DB_NAME
        fromDatabase:
          name: library-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: library-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: library-db
          property: password
      - key: DB_SYNC
        value: "true"

  # Frontend React
  - type: web
    name: library-frontend
    env: docker
    dockerContext: ./library-frontend
    dockerFilePath: ./library-frontend/Dockerfile
    plan: starter
    envVars:
      - key: VITE_API_URL
        fromService:
          name: library-api
          type: web
          property: host
